### ISSUE TITLE
代码进一步开源

### ISSUE THREAD

**Issue by luoxin-99** [gy65896/DeepSORVF#2]
你好，可否将utils包下的AIS_utils.pyc、VIS_utils.pyc、FUS_utils.pyc源代码开源，我想参考一下你们的处理方法。再次感谢！

**Comment by songwu-cs** [comment]
Well, I have exactly the same question. I sent several emails, but no reply yet.

**Comment by gy65896** [comment]
Thank you for your question. I have open sourced these three files. You can find them in the corresponding folders.
